### ISSUE TITLE
Unable To Compile In UE5 

### ISSUE THREAD

**Issue by cjm399** [jinyuliao/GenericGraph#28]
Hello! I am on the most up-to-date commit on Generic Graph (62eb887) as well as the most up-to-date source of UE5 (d9d435c). However, when I open the project up in Visual Studios, I receive the following compilation errors:

1. 'FKismetEditorUtilities': is not a class or namespace name
2. 'CanCreateBlueprintOfClass': identifier not found.

Both of these occur inside of GenericGraphFactory.cpp

So, to amend this, I did the simple thing and found the include path of FKismetEditorUtilites online and found it to be 
`#include "Kismet2/KismetEditorUtilities.h"`
Noticing that this was not included at the top of the file, I simply added it, however, it only created more errors. All of the new errors were in the form of something along the lines of 

`Error	LNK2005	"void __cdecl operator delete[](void *,unsigned __int64,struct std::nothrow_t const &)" (??_V@YAXPEAX_KAEBUnothrow_t@std@@@Z) already defined in Module.GenericGraphEditor.cpp.obj	TestDialogue	S:\dev\Unreal\Projects\TestDialogue\Intermediate\ProjectFiles\AssetEditor_GenericGraph.cpp.obj	1`

Looking at the github issues, in particular issue #24 I tried setting the bUseUnity =true inside of GenericGraphEditor.Build.cs and still get errors. Particularly:

`InitializeModule already defined in Module.GenericGraphEditor.cpp.obj`

Has anyone else had similar issues? Or gotten this plugin to compile? I have had it working and enjoyed it for a long time inside of UE4.

**Comment by Freznosis** [comment]
Just tested the latest commit of GG in my project and it is working fine. Also on latest UE5 source. Wondering if there is somewhere you might've messed up when copying over to Plugins folder? Maybe try plopping it into the engine Plugin folder instead of your project Plugin folder? Also what platform are you trying to use it on?

**Comment by cjm399** [comment]
Well, even though I must have done this 10 times. I deleted everything from the Plugins, copied it over and now it seems to work!

So, I'm not sure what I was doing before unfortunately, for anyone else in my position, but it seems to be working as intended now!
