### ISSUE TITLE
GenericGraph asserts "Unknown node type." when opening the GenericGraph asset or derived asset.

### ISSUE THREAD

**Issue by majeric** [jinyuliao/GenericGraph#4]
Context: UE4 4.17.2

It asserts in SDockingSplitter.cpp at line 153 with "Unknown node type.". Following the callstack back up, this happens as a concequence of the line 118 in AssetEditro_GenericGraph.cpp 

FAssetEditorToolkit::InitAssetEditor(Mode, InitToolkitHost, GenericGraphEditorAppName, StandaloneDefaultLayout, bCreateDefaultStandaloneMenu, bCreateDefaultToolbar, EditingGraph, false);

The following is the full callstack:

`
 	UE4Editor-Slate.dll!SDockingSplitter::CleanUpNodes() Line 153	C++
 	UE4Editor-Slate.dll!SDockingSplitter::CleanUpNodes() Line 97	C++
 	UE4Editor-Slate.dll!SDockingArea::CleanUp(SDockingNode::ELayoutModification RemovalMethod) Line 204	C++
 	UE4Editor-Slate.dll!FTabManager::RestoreArea(const TSharedRef<FTabManager::FArea,0> & AreaToRestore, const TSharedPtr<SWindow,0> & InParentWindow, const bool bEmbedTitleAreaContent) Line 1250	C++
 	UE4Editor-Slate.dll!FTabManager::RestoreFrom(const TSharedRef<FTabManager::FLayout,0> & Layout, const TSharedPtr<SWindow,0> & ParentWindow, const bool bEmbedTitleAreaContent) Line 807	C++
 	UE4Editor-UnrealEd.dll!SStandaloneAssetEditorToolkitHost::RestoreFromLayout(const TSharedRef<FTabManager::FLayout,0> & NewLayout) Line 126	C++
 	UE4Editor-UnrealEd.dll!SStandaloneAssetEditorToolkitHost::SetupInitialContent(const TSharedRef<FTabManager::FLayout,0> & DefaultLayout, const TSharedPtr<SDockTab,0> & InHostTab, const bool bCreateDefaultStandaloneMenu) Line 112	C++
 	UE4Editor-UnrealEd.dll!FAssetEditorToolkit::InitAssetEditor(const EToolkitMode::Type Mode, const TSharedPtr<IToolkitHost,0> & InitToolkitHost, const FName AppIdentifier, const TSharedRef<FTabManager::FLayout,0> & StandaloneDefaultLayout, const bool bCreateDefaultStandaloneMenu, const bool bCreateDefaultToolbar, const TArray<UObject *,FDefaultAllocator> & ObjectsToEdit, const bool bInIsToolbarFocusable) Line 218	C++
 	UE4Editor-UnrealEd.dll!FAssetEditorToolkit::InitAssetEditor(const EToolkitMode::Type Mode, const TSharedPtr<IToolkitHost,0> & InitToolkitHost, const FName AppIdentifier, const TSharedRef<FTabManager::FLayout,0> & StandaloneDefaultLayout, const bool bCreateDefaultStandaloneMenu, const bool bCreateDefaultToolbar, UObject * ObjectToEdit, const bool bInIsToolbarFocusable) Line 55	C++
>	UE4Editor-GenericGraphEditor-Win64-DebugGame.dll!FAssetEditor_GenericGraph::InitGenericGraphAssetEditor(const EToolkitMode::Type Mode, const TSharedPtr<IToolkitHost,0> & InitToolkitHost, UGenericGraph * Graph) Line 120	C++
 	UE4Editor-GenericGraphEditor-Win64-DebugGame.dll!FAssetTypeActions_GenericGraph::OpenAssetEditor(const TArray<UObject *,FDefaultAllocator> & InObjects, TSharedPtr<IToolkitHost,0> EditWithinLevelEditor) Line 36	C++
 	UE4Editor-UnrealEd.dll!FAssetEditorManager::OpenEditorForAsset(UObject * Asset, const EToolkitMode::Type ToolkitMode, TSharedPtr<IToolkitHost,0> OpenedFromLevelEditor) Line 351	C++
 	UE4Editor-GenericGraphEditor-Win64-DebugGame.dll!FAssetTypeActions_Base::AssetsActivated(const TArray<UObject *,FDefaultAllocator> & InObjects, EAssetTypeActivationMethod::Type ActivationType) Line 50	C++
 	UE4Editor-ContentBrowser.dll!SContentBrowser::OnAssetsActivated(const TArray<FAssetData,FDefaultAllocator> & ActivatedAssets, EAssetTypeActivationMethod::Type ActivationMethod) Line 1942	C++
 	UE4Editor-ContentBrowser.dll!TBaseSPMethodDelegateInstance<0,SContentBrowser,0,TTypeWrapper<void> __cdecl(TArray<FAssetData,FDefaultAllocator> const & __ptr64,enum EAssetTypeActivationMethod::Type)>::Execute(const TArray<FAssetData,FDefaultAllocator> & <Params_0>, EAssetTypeActivationMethod::Type <Params_1>) Line 327	C++
 	UE4Editor-ContentBrowser.dll!TBaseSPMethodDelegateInstance<0,SContentBrowser,0,void __cdecl(TArray<FAssetData,FDefaultAllocator> const & __ptr64,enum EAssetTypeActivationMethod::Type)>::ExecuteIfSafe(const TArray<FAssetData,FDefaultAllocator> & <Params_0>, EAssetTypeActivationMethod::Type <Params_1>) Line 434	C++
 	UE4Editor-ContentBrowser.dll!SAssetView::OnListMouseButtonDoubleClick(TSharedPtr<FAssetViewItem,0> AssetItem) Line 3864	C++
 	UE4Editor-ContentBrowser.dll!TBaseSPMethodDelegateInstance<0,SAssetView,0,TTypeWrapper<void> __cdecl(TSharedPtr<FAssetViewItem,0>)>::Execute(TSharedPtr<FAssetViewItem,0> <Params_0>) Line 327	C++
 	UE4Editor-ContentBrowser.dll!TBaseSPMethodDelegateInstance<0,SAssetView,0,void __cdecl(TSharedPtr<FAssetViewItem,0>)>::ExecuteIfSafe(TSharedPtr<FAssetViewItem,0> <Params_0>) Line 434	C++
 	UE4Editor-ContentBrowser.dll!TBaseDelegate<void,TSharedPtr<FAssetViewItem,0> >::ExecuteIfBound(TSharedPtr<FAssetViewItem,0> <Params_0>) Line 624	C++
 	UE4Editor-ContentBrowser.dll!SListView<TSharedPtr<FAssetViewItem,0> >::Private_OnItemDoubleClicked(TSharedPtr<FAssetViewItem,0> TheItem) Line 805	C++
 	UE4Editor-ContentBrowser.dll!STableRow<TSharedPtr<FAssetViewItem,0> >::OnMouseButtonDoubleClick(const FGeometry & InMyGeometry, const FPointerEvent & InMouseEvent) Line 288	C++
 	UE4Editor-Slate.dll!FSlateApplication::RoutePointerDoubleClickEvent::__l2::<lambda>(const FArrangedWidget & TargetWidget, const FPointerEvent & Event) Line 5635	C++
 	UE4Editor-Slate.dll!FEventRouter::Route<FReply,FEventRouter::FBubblePolicy,FPointerEvent,FReply <lambda>(const FArrangedWidget &, const FPointerEvent &) >(FSlateApplication * ThisApplication, FEventRouter::FBubblePolicy RoutingPolicy, FPointerEvent EventCopy, const FSlateApplication::RoutePointerDoubleClickEvent::__l2::FReply <lambda>(const FArrangedWidget &, const FPointerEvent &) & Lambda) Line 232	C++
 	UE4Editor-Slate.dll!FSlateApplication::RoutePointerDoubleClickEvent(FWidgetPath & WidgetsUnderPointer, FPointerEvent & PointerEvent) Line 5633	C++
 	UE4Editor-Slate.dll!FSlateApplication::ProcessMouseButtonDoubleClickEvent(const TSharedPtr<FGenericWindow,0> & PlatformWindow, FPointerEvent & InMouseEvent) Line 5620	C++
 	UE4Editor-Slate.dll!FSlateApplication::OnMouseDoubleClick(const TSharedPtr<FGenericWindow,0> & PlatformWindow, const EMouseButtons::Type Button, const FVector2D CursorPos) Line 5596	C++
 	UE4Editor-Core.dll!FWindowsApplication::ProcessDeferredMessage(const FDeferredWindowsMessage & DeferredMessage) Line 1722	C++
 	UE4Editor-Core.dll!FWindowsApplication::DeferMessage(TSharedPtr<FWindowsWindow,0> & NativeWindow, HWND__ * InHWnd, unsigned int InMessage, unsigned __int64 InWParam, __int64 InLParam, int MouseX, int MouseY, unsigned int RawInputFlags) Line 2161	C++
 	UE4Editor-Core.dll!FWindowsApplication::ProcessMessage(HWND__ * hwnd, unsigned int msg, unsigned __int64 wParam, __int64 lParam) Line 881	C++
 	UE4Editor-Core.dll!FWindowsApplication::AppWndProc(HWND__ * hwnd, unsigned int msg, unsigned __int64 wParam, __int64 lParam) Line 721	C++
 	user32.dll!00007ffc8fcdbc50()	Unknown
 	user32.dll!00007ffc8fcdb5cf()	Unknown
 	UE4Editor-Core.dll!FWindowsPlatformMisc::PumpMessages(bool bFromMainLoop) Line 1009	C++
 	UE4Editor.exe!FEngineLoop::Tick() Line 3151	C++
 	UE4Editor.exe!GuardedMain(const wchar_t * CmdLine, HINSTANCE__ * hInInstance, HINSTANCE__ * hPrevInstance, int nCmdShow) Line 166	C++
 	UE4Editor.exe!WinMain(HINSTANCE__ * hInInstance, HINSTANCE__ * hPrevInstance, char * __formal, int nCmdShow) Line 199	C++
 	UE4Editor.exe!__scrt_common_main_seh() Line 253	C++
 	kernel32.dll!00007ffc8ff02774()	Unknown
 	ntdll.dll!00007ffc927e0d51()	Unknown
`

**Comment by majeric** [comment]
I've done a clean up and and rebuild without success. IT's fairly consistent. Keep in mind that this is your 4.17.2 build and not synced to head. I'm not in the position to upgrade my main project to 4.18
 yet.

Here's the test project I was exploring.

[GG417.zip](https://github.com/jinyuliao/GenericGraph/files/1570082/GG417.zip)

**Comment by jinyuliao** [comment]
This is weird, i've tested your project with UE 4.17.2, still can't reproduce it.
![image](https://user-images.githubusercontent.com/2009308/34137831-c5baa5dc-e4a7-11e7-9667-709c845b80c8.png)

**Comment by majeric** [comment]
My project just compiled, ran and worked?

**Comment by jinyuliao** [comment]
yes, i download it, switch to debug mode, compile, run and it works.

**Comment by majeric** [comment]
Windows 10?

**Comment by jinyuliao** [comment]
Yes.

**Comment by majeric** [comment]
Verified 4.17.2 tried running it and it crashed. I tried uninstalling 4.17.2 and reinstalling and it crashed. This is really weird.

**Comment by majeric** [comment]
I upgraded to 4.18.2 and I tested my project on my MacBook Pro in 4.17.2 and both of them fail the same way.

**Comment by jinyuliao** [comment]
I've reproduced this problem on Mac and pushed a branch [4.17_fix_crash_on_mac](https://github.com/jinyuliao/GenericGraph/tree/4.17_fix_crash_on_mac) ,this commit works for me, can you test it?

**Comment by majeric** [comment]
That solves my problem on the windows side too. That works. :)
