### ISSUE TITLE
图表中新增节点时UGenericGraphNode内子节点之类的信息不会得到更新。

### ISSUE THREAD

**Issue by Eragon-Brisingr** [jinyuliao/GenericGraph#5]
图表中新增节点时UGenericGraphNode内子节点之类的信息不会得到更新，必须保存之后重开才会得到更新。

我在UEdGraph_GenericGraph的Modify函数下新加了一行RebuildGenericGraph()使得节点得到更新，但我觉得这个办法应该不是最优雅的。

**Comment by jinyuliao** [comment]
Save之后就会更新了。能描述一下你的使用场景么，为什么新增Node时就需要子节点的信息？

**Comment by Eragon-Brisingr** [comment]
我想根据现有子节点的数量来判断是否能新增连线。

**Comment by jinyuliao** [comment]
建议修改UAssetGraphSchema_GenericGraph::CanCreateConnection，使用UEdGraphPin.LinkedTo来判断子节点的数目。

GenericGraphRuntime里的类都有其对应的Editor版本，Editor相关的功能扩展请尽量使用UEdxxx相关的类

GameLogic | Editor
------------ | ------
UGenericGraph | UEdGraph_GenericGraph
UGenericGraphNode | UEdNode_GenericGraphNode
UGenericGraphEdge |  UEdNode_GenericGraphEdge

UGenericGraphNode::CanCreateConnection只是为了作一些简单的定制而设计，并不希望用户添加过多的Editor定制代码(或许应该删除这个接口防止误用)。
如果一定要让UGenericGraphNode的子节点信息保持最新，至少执行以下操作时需要rebuild:
* 新增节点
* 删除节点
* UAssetGraphSchema_GenericGraph::BreakNodeLinks
* UAssetGraphSchema_GenericGraph::BreakPinLinks
* UAssetGraphSchema_GenericGraph::BreakSinglePinLink
* UAssetGraphSchema_GenericGraph::DropPinOnNode

**Comment by Eragon-Brisingr** [comment]
谢谢了，我需要的效果应该要修改一部分Editor那块的代码了。
