### ISSUE TITLE
Cannot compile

### ISSUE THREAD

**Issue by rupee990** [jinyuliao/GenericGraph#6]
Hello, 

I cannot seem to compile the code, I get the following error:

'initializing' cannot convert from 'ValueType *' to 'TSharedPtr<SGraphPtr<SGraphPin,0>'

in the ConnectionDrawingPolicy_GenericGraph.cpp

**Comment by jinyuliao** [comment]
hello, can you tell me your UE version?

**Comment by rupee990** [comment]
Yes sorry, 

Im using UE 4.22.3

I was able to compile it by changing this line:

TSharedPtr<SGraphPin>* pTargetWidget = PinToPinWidgetMap.Find(InputPin)

To

TSharedRef<SGraphPin>* pTargetWidget = PinToPinWidgetMap.Find(InputPin

**Comment by jinyuliao** [comment]
for UE 4.22, you can use branch [4.22](https://github.com/jinyuliao/GenericGraph/tree/4.22).
master branch will follow latest UE release

**Comment by rupee990** [comment]
Alright will try that thank you, say are you aware of any documentation for creating a custom graph in unreal? I haven't found any.

**Comment by jinyuliao** [comment]
i can't find any documentation too, i think for now the only way is to read the source code :pensive:

**Comment by rupee990** [comment]
I have been reading your source code too, its very easy to read! thank you for this!
